name: rise_ui_demos
description: rise_ui_demos
version: 0.1.0
homepage: https://github.com/leanflutter/rise_ui/tree/main/packages/rise_ui_demos

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  rise_ui: ^0.1.0
  open_color: ^0.1.0
  tabler_icon_library: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  rise_ui_test:
    path: ../rise_ui_test
