name: influxui_test
description: influxui_test
version: 0.1.0
homepage: https://github.com/leanflutter/influxui/tree/main/packages/influxui_test

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  influxui: ^0.1.0

dev_dependencies:
  mostly_reasonable_lints: ^0.1.2

flutter:
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.otf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
