name: tabler_icon_library
description: tabler_icon_library
version: 0.1.0
homepage: https://github.com/leanflutter/rise_ui/tree/main/packages/tabler_icon_library

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  recase: ^4.1.0

flutter:
  fonts:
    - family: tabler-icons
      fonts:
        - asset: fonts/tabler-icons.ttf
