name: rise_ui_test
description: rise_ui_test
version: 0.1.0
homepage: https://github.com/leanflutter/rise_ui/tree/main/packages/rise_ui_test

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  rise_ui: ^0.1.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono/RobotoMono-Regular.ttf
