name: influxui
description: influxui
version: 0.0.1
homepage: https://github.com/leanflutter/influxui/tree/main/packages/influxui

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.3
  gap: ^3.0.1
  theme_tailor_annotation: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  influxui_test:
    path: ../influxui_test
  mostly_reasonable_lints: ^0.1.2
  theme_tailor: ^2.0.2
