name: rise_ui
description: rise_ui
version: 0.1.0
homepage: https://github.com/leanflutter/rise_ui/tree/main/packages/rise_ui

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.3
  theme_tailor_annotation: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1
  rise_ui_test:
    path: ../rise_ui_test
  theme_tailor: ^2.0.2
