name: base_ui
description: base_ui
version: 0.1.0
homepage: https://github.com/leanflutter/base_ui/tree/main/packages/base_ui

environment:
  sdk: ">=2.19.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  base_ui_core: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
