builders:
  storybook_dart:
    import: "package:storybook_dart_generator/builder.dart"
    builder_factories: ["storybookDartBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
