name: gallery
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.17.1
  device_info_plus: ^8.1.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_web_plugins:
    sdk: flutter
  go_router: ^13.0.0
  path: ^1.8.3
  path_provider: ^2.0.15
  pointer_interceptor: ^0.9.3+7
  rise_ui: ^0.1.0
  rise_ui_demos: ^0.1.0
  shared_preferences: ^2.1.0
  tabler_icon_library: ^0.1.0
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  uses-material-design: true
