name: preview_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  rise_ui: ^0.1.0
  storybook_dart: ^0.1.0
  storybook_dart_annotation: ^0.1.0
  tabler_icon_library: ^0.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  storybook_dart_generator: ^0.1.0

dependency_overrides:
  storybook_dart:
    path: ../../../storybook_dart/packages/storybook_dart
  storybook_dart_annotation:
    path: ../../../storybook_dart/packages/storybook_dart_annotation
  storybook_dart_generator:
    path: ../../../storybook_dart/packages/storybook_dart_generator

flutter:
  uses-material-design: true
